// <auto-generated />
using System;
using IST_Submission_Form.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IST_Submission_Form.Migrations.Comment
{
    [DbContext(typeof(CommentContext))]
    partial class CommentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IST_Submission_Form.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<int>("SubmissionID");

                    b.HasKey("ID");

                    b.HasIndex("SubmissionID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("IST_Submission_Form.Models.Submission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Goal");

                    b.Property<string>("LastName");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("text");

                    b.Property<string>("Timeline");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Submission");
                });

            modelBuilder.Entity("IST_Submission_Form.Models.Comment", b =>
                {
                    b.HasOne("IST_Submission_Form.Models.Submission", "Submission")
                        .WithMany("Comments")
                        .HasForeignKey("SubmissionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
